<a href="https://colab.research.google.com/github/monifonse/Deber/blob/main/Moni_caso_1_DIOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range (1,74,1):
  print(f"hola monica {i}")

hola monica 1
hola monica 2
hola monica 3
hola monica 4
hola monica 5
hola monica 6
hola monica 7
hola monica 8
hola monica 9
hola monica 10
hola monica 11
hola monica 12
hola monica 13
hola monica 14
hola monica 15
hola monica 16
hola monica 17
hola monica 18
hola monica 19
hola monica 20
hola monica 21
hola monica 22
hola monica 23
hola monica 24
hola monica 25
hola monica 26
hola monica 27
hola monica 28
hola monica 29
hola monica 30
hola monica 31
hola monica 32
hola monica 33
hola monica 34
hola monica 35
hola monica 36
hola monica 37
hola monica 38
hola monica 39
hola monica 40
hola monica 41
hola monica 42
hola monica 43
hola monica 44
hola monica 45
hola monica 46
hola monica 47
hola monica 48
hola monica 49
hola monica 50
hola monica 51
hola monica 52
hola monica 53
hola monica 54
hola monica 55
hola monica 56
hola monica 57
hola monica 58
hola monica 59
hola monica 60
hola monica 61
hola monica 62
hola monica 63
hola monica 64
hola monica 65
hola monica 66
hola monica 67
hola monica 68
hola monica 69
hola monica 70
hola monica 71
hola monica 72
hola monica 73

In [ ]:
fibonacci = (0,1,1,2,3,5,8,13,21,34,21+89)
print(fibonacci)

a = 0
b = 1
serie = []
for i in range(1,72,1):
  serie.append (a)
  print(a)
  print(serie)
  c = a+b
  a = b
  b = c

(0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 110)
0
[0]
1
[0, 1]
1
[0, 1, 1]
2
[0, 1, 1, 2]
3
[0, 1, 1, 2, 3]
5
[0, 1, 1, 2, 3, 5]
8
[0, 1, 1, 2, 3, 5, 8]
13
[0, 1, 1, 2, 3, 5, 8, 13]
21
[0, 1, 1, 2, 3, 5, 8, 13, 21]
34
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
55
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
89
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
144
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]
233
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]
377
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]
610
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610]
987
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]
1597
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]
2584
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584]
4181
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]
6765
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]
10946
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946]
17711
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711]
28657
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657]
46368
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368]
75025
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025]
121393
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393]
196418
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418]
317811
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811]
514229
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229]
832040
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040]
1346269
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269]
2178309
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309]
3524578
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578]
5702887
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887]
9227465
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465]
14930352
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352]
24157817
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817]
39088169
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169]
63245986
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986]
102334155
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155]
165580141
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141]
267914296
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296]
433494437
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437]
701408733
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733]
1134903170
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170]
1836311903
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903]
2971215073
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073]
4807526976
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976]
7778742049
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049]
12586269025
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025]
20365011074
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074]
32951280099
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099]
53316291173
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173]
86267571272
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272]
139583862445
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445]
225851433717
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717]
365435296162
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162]
591286729879
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879]
956722026041
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041]
1548008755920
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920]
2504730781961
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961]
4052739537881
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881]
6557470319842
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842]
10610209857723
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723]
17167680177565
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565]
27777890035288
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288]
44945570212853
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853]
72723460248141
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141]
117669030460994
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141, 117669030460994]
190392490709135
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141, 117669030460994, 190392490709135]

In [ ]:
from numpy import linspace
x = linspace (0,4,201)
print (x)

[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2  0.22 0.24 0.26
 0.28 0.3  0.32 0.34 0.36 0.38 0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54
 0.56 0.58 0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78 0.8  0.82
 0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98 1.   1.02 1.04 1.06 1.08 1.1
 1.12 1.14 1.16 1.18 1.2  1.22 1.24 1.26 1.28 1.3  1.32 1.34 1.36 1.38
 1.4  1.42 1.44 1.46 1.48 1.5  1.52 1.54 1.56 1.58 1.6  1.62 1.64 1.66
 1.68 1.7  1.72 1.74 1.76 1.78 1.8  1.82 1.84 1.86 1.88 1.9  1.92 1.94
 1.96 1.98 2.   2.02 2.04 2.06 2.08 2.1  2.12 2.14 2.16 2.18 2.2  2.22
 2.24 2.26 2.28 2.3  2.32 2.34 2.36 2.38 2.4  2.42 2.44 2.46 2.48 2.5
 2.52 2.54 2.56 2.58 2.6  2.62 2.64 2.66 2.68 2.7  2.72 2.74 2.76 2.78
 2.8  2.82 2.84 2.86 2.88 2.9  2.92 2.94 2.96 2.98 3.   3.02 3.04 3.06
 3.08 3.1  3.12 3.14 3.16 3.18 3.2  3.22 3.24 3.26 3.28 3.3  3.32 3.34
 3.36 3.38 3.4  3.42 3.44 3.46 3.48 3.5  3.52 3.54 3.56 3.58 3.6  3.62
 3.64 3.66 3.68 3.7  3.72 3.74 3.76 3.78 3.8  3.82 3.84 3.86 3.88 3.9
 3.92 3.94 3.96 3.98 4.  ]

In [ ]:
from numpy import linspace
from pandas import DataFrame
dicc = {
    "t": linspace(0,4,201),
}
print(dicc)

{'t': array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  , 1.02, 1.04, 1.06, 1.08,
       1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 , 1.22, 1.24, 1.26, 1.28, 1.3 ,
       1.32, 1.34, 1.36, 1.38, 1.4 , 1.42, 1.44, 1.46, 1.48, 1.5 , 1.52,
       1.54, 1.56, 1.58, 1.6 , 1.62, 1.64, 1.66, 1.68, 1.7 , 1.72, 1.74,
       1.76, 1.78, 1.8 , 1.82, 1.84, 1.86, 1.88, 1.9 , 1.92, 1.94, 1.96,
       1.98, 2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18,
       2.2 , 2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 ,
       2.42, 2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62,
       2.64, 2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84,
       2.86, 2.88, 2.9 , 2.92, 2.94, 2.96, 2.98, 3.  , 3.02, 3.04, 3.06,
       3.08, 3.1 , 3.12, 3.14, 3.16, 3.18, 3.2 , 3.22, 3.24, 3.26, 3.28,
       3.3 , 3.32, 3.34, 3.36, 3.38, 3.4 , 3.42, 3.44, 3.46, 3.48, 3.5 ,
       3.52, 3.54, 3.56, 3.58, 3.6 , 3.62, 3.64, 3.66, 3.68, 3.7 , 3.72,
       3.74, 3.76, 3.78, 3.8 , 3.82, 3.84, 3.86, 3.88, 3.9 , 3.92, 3.94,
       3.96, 3.98, 4.  ])}

In [ ]:
import pandas as pd
import numpy as np
col1 = np.linspace(0, 4, 201)
df = pd.DataFrame(col1, columns=['t'])
df['s'] = df['t'].apply(np.sin)
print(df)

        t         s
0    0.00  0.000000
1    0.02  0.019999
2    0.04  0.039989
3    0.06  0.059964
4    0.08  0.079915
..    ...       ...
196  3.92 -0.702146
197  3.94 -0.716246
198  3.96 -0.730058
199  3.98 -0.743579
200  4.00 -0.756802

[201 rows x 2 columns]

In [ ]:
df ["s10"] = df["s"].shift(10)
print(df.head(10))

      t         s  s10
0  0.00  0.000000  NaN
1  0.02  0.019999  NaN
2  0.04  0.039989  NaN
3  0.06  0.059964  NaN
4  0.08  0.079915  NaN
5  0.10  0.099833  NaN
6  0.12  0.119712  NaN
7  0.14  0.139543  NaN
8  0.16  0.159318  NaN
9  0.18  0.179030  NaN

In [ ]:
df ["d"] = df ["s"] - df ["s10"]
print (df)

        t         s       s10         d
0    0.00  0.000000       NaN       NaN
1    0.02  0.019999       NaN       NaN
2    0.04  0.039989       NaN       NaN
3    0.06  0.059964       NaN       NaN
4    0.08  0.079915       NaN       NaN
..    ...       ...       ...       ...
196  3.92 -0.702146 -0.546691 -0.155455
197  3.94 -0.716246 -0.563327 -0.152918
198  3.96 -0.730058 -0.579738 -0.150320
199  3.98 -0.743579 -0.595917 -0.147662
200  4.00 -0.756802 -0.611858 -0.144945

[201 rows x 4 columns]

In [ ]:
def is_positive(x):
  if x> 0:
    return 1
  else:
    return 0

df['p'] = df['d'].apply(lambda x: is_positive(x)) 
df

        t         s       s10         d  p
0    0.00  0.000000       NaN       NaN  0
1    0.02  0.019999       NaN       NaN  0
2    0.04  0.039989       NaN       NaN  0
3    0.06  0.059964       NaN       NaN  0
4    0.08  0.079915       NaN       NaN  0
..    ...       ...       ...       ... ..
196  3.92 -0.702146 -0.546691 -0.155455  0
197  3.94 -0.716246 -0.563327 -0.152918  0
198  3.96 -0.730058 -0.579738 -0.150320  0
199  3.98 -0.743579 -0.595917 -0.147662  0
200  4.00 -0.756802 -0.611858 -0.144945  0

[201 rows x 5 columns]

In [ ]:
df.to_csv('my_df.csv',sep = ';')

# Sección nueva

# Sección nueva

In [ ]:
df

  col1  col2  media
0    A     1    2.5
1    B     2    2.0
2    A     4    2.5

In [ ]:
df['m'] = df.groupby('p')['d'].transform('mean')
print (df)

        t         s       s10         d  p         m
0    0.00  0.000000       NaN       NaN  0 -0.144632
1    0.02  0.019999       NaN       NaN  0 -0.144632
2    0.04  0.039989       NaN       NaN  0 -0.144632
3    0.06  0.059964       NaN       NaN  0 -0.144632
4    0.08  0.079915       NaN       NaN  0 -0.144632
..    ...       ...       ...       ... ..       ...
196  3.92 -0.702146 -0.546691 -0.155455  0 -0.144632
197  3.94 -0.716246 -0.563327 -0.152918  0 -0.144632
198  3.96 -0.730058 -0.579738 -0.150320  0 -0.144632
199  3.98 -0.743579 -0.595917 -0.147662  0 -0.144632
200  4.00 -0.756802 -0.611858 -0.144945  0 -0.144632

[201 rows x 6 columns]

In [ ]:
#MODIFY EACH STEP IN ORDER TO RUN COMPLETLY THE PROGRAM
print('STEP 1')

for i in range(0,11):
  x = i

print(f'x should be 10:{x}')
if x == 10:
    print('SUCCESS! IN STEP 1')
print('STEP 2')
x = False

for i in range(0,11):
    x = x or True
    if x and  i == 5:
        break 
    

print(f'x should be True:{x}')
print(f'i should be 5:{i}')
if i == 5 and x:
    print('SUCCESS! IN STEP 2')

STEP 1
x should be 10:10
SUCCESS! IN STEP 1
STEP 2
x should be True:True
i should be 5:5
SUCCESS! IN STEP 2

In [ ]:
y = 73
for x in range (2, y):
  if y%x == 0:
      result = False
      break
if y == x + 1:
  result = True
print (result)

True

In [ ]:
def is_prime (y):
  for x in range (2, y):
    if y%x == 0:
        result = False
        break
  if y == x + 1:
    result = True
  return result
is_prime(5)

True

In [ ]:
contador = 0
last_prime = 1
next_number = 2
print (2)
while contador<72:
  next_number = next_number + 1
  if is_prime (next_number):
    contador = contador + 1
    last_prime = next_number 
print (last_prime)

2
367

In [ ]:
import pandas as holaquetal
df = holaquetal.DataFrame(data = {'col1': ['A','B','A'],'col2': [1,2,4]})
df['media'] = df.groupby('col1')['col2'].transform('mean')
df.size

9

In [ ]:
df.to_csv('my_df.csv',sep = ';')

In [ ]:
# Declaramos la funcion de numero primo 
def primo(numero):
  if numero == 0 or numero == 1 or numero == 4:
    return False
  for x in range (2, int(numero/2)):
    if numero % x == 0:
      return False
  return True
# Utilizamos la sentencia while mientras encuentra los 73 numeros no primos
i = 0
j = 0
while True:
      es_primo = primo(i)
      if es_primo:
          i+=1
      else:
         print("No es primo",i)
         i+= 1
         j+= 1
      if j == 73:
       break

No es primo 0
No es primo 1
No es primo 4
No es primo 6
No es primo 8
No es primo 9
No es primo 10
No es primo 12
No es primo 14
No es primo 15
No es primo 16
No es primo 18
No es primo 20
No es primo 21
No es primo 22
No es primo 24
No es primo 25
No es primo 26
No es primo 27
No es primo 28
No es primo 30
No es primo 32
No es primo 33
No es primo 34
No es primo 35
No es primo 36
No es primo 38
No es primo 39
No es primo 40
No es primo 42
No es primo 44
No es primo 45
No es primo 46
No es primo 48
No es primo 49
No es primo 50
No es primo 51
No es primo 52
No es primo 54
No es primo 55
No es primo 56
No es primo 57
No es primo 58
No es primo 60
No es primo 62
No es primo 63
No es primo 64
No es primo 65
No es primo 66
No es primo 68
No es primo 69
No es primo 70
No es primo 72
No es primo 74
No es primo 75
No es primo 76
No es primo 77
No es primo 78
No es primo 80
No es primo 81
No es primo 82
No es primo 84
No es primo 85
No es primo 86
No es primo 87
No es primo 88
No es primo 90
No es primo 91
No es primo 92
No es primo 93
No es primo 94
No es primo 95
No es primo 96

In [ ]:
def is_prime(y):
  for x in range (2,y):
    if y%x == 0:
        result = False
        break
  if y == x + 1:
    result = True
  return result
is_prime(104)

False

In [ ]:
contador = 0
last_prime = 1
next_number = last_prime + 1
while contador<10:
  next_number = next_number + 1
  if is_prime (next_number):
    contador = contador + 1
    last_prime = next_number
    print (last_prime)

3
5
7
11
13
17
19
23
29
31

In [ ]:
def primo(numero):
  if numero == 0 or numero == 1 or numero == 4:
    return 0
  for x in range(2, int(numero/2)):
    if numero%x == 0:
      return 0
    return 1

contador = 0
anterior = 1
proximo =2
while contador < 10:
  proximo = proximo + 1
  if primo(proximo) == 0:
    contador = contador +1
    anterior = proximo
    print (anterior)

4
6
8
10
12
14
16
18
20
22

MODO DIOS

In [ ]:
primos=[]
for i in lista:
    c=0
    for j in range(1,i):
        if i%j==0:
            c+=1
    if c==1:
        primos.append(i)
print(primos)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217, 1223, 1229, 1231, 1237, 1249, 1259, 1277, 1279, 1283, 1289, 1291, 1297, 1301, 1303, 1307, 1319, 1321, 1327, 1361, 1367, 1373, 1381, 1399, 1409, 1423, 1427, 1429, 1433, 1439, 1447, 1451, 1453, 1459, 1471, 1481, 1483, 1487, 1489, 1493, 1499, 1511, 1523, 1531, 1543, 1549, 1553, 1559, 1567, 1571, 1579, 1583, 1597, 1601, 1607, 1609, 1613, 1619, 1621, 1627, 1637, 1657, 1663, 1667, 1669, 1693, 1697, 1699, 1709, 1721, 1723, 1733, 1741, 1747, 1753, 1759, 1777, 1783, 1787, 1789, 1801, 1811, 1823, 1831, 1847, 1861, 1867, 1871, 1873, 1877, 1879, 1889, 1901, 1907, 1913, 1931, 1933, 1949, 1951, 1973, 1979, 1987, 1993, 1997, 1999, 2003, 2011, 2017, 2027, 2029, 2039, 2053, 2063, 2069, 2081, 2083, 2087, 2089, 2099, 2111, 2113, 2129, 2131, 2137, 2141, 2143, 2153, 2161, 2179, 2203, 2207, 2213, 2221, 2237, 2239, 2243, 2251, 2267, 2269, 2273, 2281, 2287, 2293, 2297, 2309, 2311, 2333, 2339, 2341, 2347, 2351, 2357, 2371, 2377, 2381, 2383, 2389, 2393, 2399, 2411, 2417, 2423, 2437, 2441, 2447, 2459, 2467, 2473, 2477, 2503, 2521, 2531, 2539, 2543, 2549, 2551, 2557, 2579, 2591, 2593, 2609, 2617, 2621, 2633, 2647, 2657, 2659, 2663, 2671, 2677, 2683, 2687, 2689, 2693, 2699, 2707, 2711, 2713, 2719, 2729, 2731, 2741, 2749, 2753, 2767, 2777, 2789, 2791, 2797, 2801, 2803, 2819, 2833, 2837, 2843, 2851, 2857, 2861, 2879, 2887, 2897, 2903, 2909, 2917, 2927, 2939, 2953, 2957, 2963, 2969, 2971, 2999, 3001, 3011, 3019, 3023, 3037, 3041, 3049, 3061, 3067, 3079, 3083, 3089, 3109, 3119, 3121, 3137, 3163, 3167, 3169, 3181, 3187, 3191, 3203, 3209, 3217, 3221, 3229, 3251, 3253, 3257, 3259, 3271, 3299, 3301, 3307, 3313, 3319, 3323, 3329, 3331, 3343, 3347, 3359, 3361, 3371, 3373, 3389, 3391, 3407, 3413, 3433, 3449, 3457, 3461, 3463, 3467, 3469, 3491, 3499, 3511, 3517, 3527, 3529, 3533, 3539, 3541, 3547, 3557, 3559, 3571, 3581, 3583, 3593, 3607, 3613, 3617, 3623, 3631, 3637, 3643, 3659, 3671, 3673, 3677, 3691, 3697, 3701, 3709, 3719, 3727, 3733, 3739, 3761, 3767, 3769, 3779, 3793, 3797, 3803, 3821, 3823, 3833, 3847, 3851, 3853, 3863, 3877, 3881, 3889, 3907, 3911, 3917, 3919, 3923, 3929, 3931, 3943, 3947, 3967, 3989, 4001, 4003, 4007, 4013, 4019, 4021, 4027, 4049, 4051, 4057, 4073, 4079, 4091, 4093, 4099, 4111, 4127, 4129, 4133, 4139, 4153, 4157, 4159, 4177, 4201, 4211, 4217, 4219, 4229, 4231, 4241, 4243, 4253, 4259, 4261, 4271, 4273, 4283, 4289, 4297, 4327, 4337, 4339, 4349, 4357, 4363, 4373, 4391, 4397, 4409, 4421, 4423, 4441, 4447, 4451, 4457, 4463, 4481, 4483, 4493, 4507, 4513, 4517, 4519, 4523, 4547, 4549, 4561, 4567, 4583, 4591, 4597, 4603, 4621, 4637, 4639, 4643, 4649, 4651, 4657, 4663, 4673, 4679, 4691, 4703, 4721, 4723, 4729, 4733, 4751, 4759, 4783, 4787, 4789, 4793, 4799, 4801, 4813, 4817, 4831, 4861, 4871, 4877, 4889, 4903, 4909, 4919, 4931, 4933, 4937, 4943, 4951, 4957, 4967, 4969, 4973, 4987, 4993, 4999, 5003, 5009, 5011, 5021, 5023, 5039, 5051, 5059, 5077, 5081, 5087, 5099, 5101, 5107, 5113, 5119, 5147, 5153, 5167, 5171, 5179, 5189, 5197, 5209, 5227, 5231, 5233, 5237, 5261, 5273, 5279, 5281, 5297, 5303, 5309, 5323, 5333, 5347, 5351, 5381, 5387, 5393, 5399, 5407, 5413, 5417, 5419, 5431, 5437, 5441, 5443, 5449, 5471, 5477, 5479, 5483, 5501, 5503, 5507, 5519, 5521, 5527, 5531, 5557, 5563, 5569, 5573, 5581, 5591, 5623, 5639, 5641, 5647, 5651, 5653, 5657, 5659, 5669, 5683, 5689, 5693, 5701, 5711, 5717, 5737, 5741, 5743, 5749, 5779, 5783, 5791, 5801, 5807, 5813, 5821, 5827, 5839, 5843, 5849, 5851, 5857, 5861, 5867, 5869, 5879, 5881, 5897, 5903, 5923, 5927, 5939, 5953, 5981, 5987, 6007, 6011, 6029, 6037, 6043, 6047, 6053, 6067, 6073, 6079, 6089, 6091, 6101, 6113, 6121, 6131, 6133, 6143, 6151, 6163, 6173, 6197, 6199, 6203, 6211, 6217, 6221, 6229, 6247, 6257, 6263, 6269, 6271, 6277, 6287, 6299, 6301, 6311, 6317, 6323, 6329, 6337, 6343, 6353, 6359, 6361, 6367, 6373, 6379, 6389, 6397, 6421, 6427, 6449, 6451, 6469, 6473, 6481, 6491, 6521, 6529, 6547, 6551, 6553, 6563, 6569, 6571, 6577, 6581, 6599, 6607, 6619, 6637, 6653, 6659, 6661, 6673, 6679, 6689, 6691, 6701, 6703, 6709, 6719, 6733, 6737, 6761, 6763, 6779, 6781, 6791, 6793, 6803, 6823, 6827, 6829, 6833, 6841, 6857, 6863, 6869, 6871, 6883, 6899, 6907, 6911, 6917, 6947, 6949, 6959, 6961, 6967, 6971, 6977, 6983, 6991, 6997, 7001, 7013, 7019, 7027, 7039, 7043, 7057, 7069, 7079, 7103, 7109, 7121, 7127, 7129, 7151, 7159, 7177, 7187, 7193, 7207, 7211, 7213, 7219, 7229, 7237, 7243, 7247, 7253, 7283, 7297, 7307, 7309, 7321, 7331, 7333, 7349, 7351, 7369, 7393, 7411, 7417, 7433, 7451, 7457, 7459, 7477, 7481, 7487, 7489, 7499, 7507, 7517, 7523, 7529, 7537, 7541, 7547, 7549, 7559, 7561, 7573, 7577, 7583, 7589, 7591, 7603, 7607, 7621, 7639, 7643, 7649, 7669, 7673, 7681, 7687, 7691, 7699, 7703, 7717, 7723, 7727, 7741, 7753, 7757, 7759, 7789, 7793, 7817, 7823, 7829, 7841, 7853, 7867, 7873, 7877, 7879, 7883, 7901, 7907, 7919, 7927, 7933, 7937, 7949, 7951, 7963, 7993, 8009, 8011, 8017, 8039, 8053, 8059, 8069, 8081, 8087, 8089, 8093, 8101, 8111, 8117, 8123, 8147, 8161, 8167, 8171, 8179, 8191, 8209, 8219, 8221, 8231, 8233, 8237, 8243, 8263, 8269, 8273, 8287, 8291, 8293, 8297, 8311, 8317, 8329, 8353, 8363, 8369, 8377, 8387, 8389, 8419, 8423, 8429, 8431, 8443, 8447, 8461, 8467, 8501, 8513, 8521, 8527, 8537, 8539, 8543, 8563, 8573, 8581, 8597, 8599, 8609, 8623, 8627, 8629, 8641, 8647, 8663, 8669, 8677, 8681, 8689, 8693, 8699, 8707, 8713, 8719, 8731, 8737, 8741, 8747, 8753, 8761, 8779, 8783, 8803, 8807, 8819, 8821, 8831, 8837, 8839, 8849, 8861, 8863, 8867, 8887, 8893, 8923, 8929, 8933, 8941, 8951, 8963, 8969, 8971, 8999, 9001, 9007, 9011, 9013, 9029, 9041, 9043, 9049, 9059, 9067, 9091, 9103, 9109, 9127, 9133, 9137, 9151, 9157, 9161, 9173, 9181, 9187, 9199, 9203, 9209, 9221, 9227, 9239, 9241, 9257, 9277, 9281, 9283, 9293, 9311, 9319, 9323, 9337, 9341, 9343, 9349, 9371, 9377, 9391, 9397, 9403, 9413, 9419, 9421, 9431, 9433, 9437, 9439, 9461, 9463, 9467, 9473, 9479, 9491, 9497, 9511, 9521, 9533, 9539, 9547, 9551, 9587, 9601, 9613, 9619, 9623, 9629, 9631, 9643, 9649, 9661, 9677, 9679, 9689, 9697, 9719, 9721, 9733, 9739, 9743, 9749, 9767, 9769, 9781, 9787, 9791, 9803, 9811, 9817, 9829, 9833, 9839, 9851, 9857, 9859, 9871, 9883, 9887, 9901, 9907, 9923, 9929, 9931, 9941, 9949, 9967, 9973]

In [ ]:
def productonúmeros(n):
    producto = 1
 
    # NÚMERO ENTERO A CADENA
    ncadena = str(n)
     
    # A TRAVÉS DE LA CADENA
    for k in ncadena:
        producto = producto * int(k)
    return producto

In [ ]:
rimosyproductoind=[]
for l in primos:
    #Solo números compuestos por dígitos
    if l>9:
        if productonúmeros(l) == primos.index(l)+1:
            primosyproductoind.append(l)
print(primosyproductoind)

[17, 73, 17, 73]

In [ ]:
primosyproductoind=[]
for l in primos:
    #Solo números compuestos por dígitos
    if l>9:
        if productonúmeros(l) == primos.index(l)+1:
            primosyproductoind.append(l)

print('Los números que cumplieron son ')
print('')
print(primosyproductoind)

Los números que cumplieron son

[17, 73]

In [ ]:
reversodeprimos=[]
for m in primos:
    a=int(str(m)[::-1])
    reversodeprimos.append(a)
print(reversodeprimos)

[2, 3, 5, 7, 11, 31, 71, 91, 32, 92, 13, 73, 14, 34, 74, 35, 95, 16, 76, 17, 37, 97, 38, 98, 79, 101, 301, 701, 901, 311, 721, 131, 731, 931, 941, 151, 751, 361, 761, 371, 971, 181, 191, 391, 791, 991, 112, 322, 722, 922, 332, 932, 142, 152, 752, 362, 962, 172, 772, 182, 382, 392, 703, 113, 313, 713, 133, 733, 743, 943, 353, 953, 763, 373, 973, 383, 983, 793, 104, 904, 914, 124, 134, 334, 934, 344, 944, 754, 164, 364, 764, 974, 784, 194, 994, 305, 905, 125, 325, 145, 745, 755, 365, 965, 175, 775, 785, 395, 995, 106, 706, 316, 716, 916, 136, 146, 346, 746, 356, 956, 166, 376, 776, 386, 196, 107, 907, 917, 727, 337, 937, 347, 157, 757, 167, 967, 377, 787, 797, 908, 118, 128, 328, 728, 928, 938, 358, 758, 958, 368, 778, 188, 388, 788, 709, 119, 919, 929, 739, 149, 749, 359, 769, 179, 779, 389, 199, 799, 9001, 3101, 9101, 1201, 1301, 3301, 9301, 9401, 1501, 1601, 3601, 9601, 7801, 1901, 3901, 7901, 3011, 9011, 7111, 3211, 9211, 1511, 3511, 3611, 1711, 1811, 7811, 3911, 1021, 3121, 7121, 3221, 9221, 1321, 7321, 9421, 9521, 7721, 9721, 3821, 9821, 1921, 7921, 1031, 3031, 7031, 9131, 1231, 7231, 1631, 7631, 3731, 1831, 9931, 9041, 3241, 7241, 9241, 3341, 9341, 7441, 1541, 3541, 9541, 1741, 1841, 3841, 7841, 9841, 3941, 9941, 1151, 3251, 1351, 3451, 9451, 3551, 9551, 7651, 1751, 9751, 3851, 7951, 1061, 7061, 9061, 3161, 9161, 1261, 7261, 7361, 7561, 3661, 7661, 9661, 3961, 7961, 9961, 9071, 1271, 3271, 3371, 1471, 7471, 3571, 9571, 7771, 3871, 7871, 9871, 1081, 1181, 3281, 1381, 7481, 1681, 7681, 1781, 3781, 7781, 9781, 9881, 1091, 7091, 3191, 1391, 3391, 9491, 1591, 3791, 9791, 7891, 3991, 7991, 9991, 3002, 1102, 7102, 7202, 9202, 9302, 3502, 3602, 9602, 1802, 3802, 7802, 9802, 9902, 1112, 3112, 9212, 1312, 7312, 1412, 3412, 3512, 1612, 9712, 3022, 7022, 3122, 1222, 7322, 9322, 3422, 1522, 7622, 9622, 3722, 1822, 7822, 3922, 7922, 9032, 1132, 3332, 9332, 1432, 7432, 1532, 7532, 1732, 7732, 1832, 3832, 9832, 3932, 9932, 1142, 7142, 3242, 7342, 1442, 7442, 9542, 7642, 3742, 7742, 3052, 1252, 1352, 9352, 3452, 9452, 1552, 7552, 9752, 1952, 3952, 9062, 7162, 1262, 3362, 7462, 7562, 9562, 3662, 1762, 7762, 3862, 7862, 9862, 3962, 9962, 7072, 1172, 3172, 9172, 9272, 1372, 1472, 9472, 3572, 7672, 7772, 9872, 1972, 7972, 1082, 3082, 9182, 3382, 7382, 3482, 1582, 7582, 1682, 9782, 7882, 7982, 3092, 9092, 7192, 7292, 9392, 3592, 7592, 3692, 9692, 1792, 9992, 1003, 1103, 9103, 3203, 7303, 1403, 9403, 1603, 7603, 9703, 3803, 9803, 9013, 9113, 1213, 7313, 3613, 7613, 9613, 1813, 7813, 1913, 3023, 9023, 7123, 1223, 9223, 1523, 3523, 7523, 9523, 1723, 9923, 1033, 7033, 3133, 9133, 3233, 9233, 1333, 3433, 7433, 9533, 1633, 1733, 3733, 9833, 1933, 7043, 3143, 3343, 9443, 7543, 1643, 3643, 7643, 9643, 1943, 9943, 1153, 7153, 7253, 9253, 3353, 9353, 1453, 7453, 7553, 9553, 1753, 1853, 3853, 3953, 7063, 3163, 7163, 3263, 1363, 7363, 3463, 9563, 1763, 3763, 7763, 1963, 7963, 1073, 9073, 9173, 7273, 3373, 9373, 1673, 7673, 9673, 9773, 3973, 7973, 3083, 1283, 3283, 3383, 7483, 1583, 3583, 3683, 7783, 1883, 9883, 7093, 1193, 7193, 9193, 3293, 9293, 1393, 3493, 7493, 7693, 9893, 1004, 3004, 7004, 3104, 9104, 1204, 7204, 9404, 1504, 7504, 3704, 9704, 1904, 3904, 9904, 1114, 7214, 9214, 3314, 9314, 3514, 7514, 9514, 7714, 1024, 1124, 7124, 9124, 9224, 1324, 1424, 3424, 3524, 9524, 1624, 1724, 3724, 3824, 9824, 7924, 7234, 7334, 9334, 9434, 7534, 3634, 3734, 1934, 7934, 9044, 1244, 3244, 1444, 7444, 1544, 7544, 3644, 1844, 3844, 3944, 7054, 3154, 7154, 9154, 3254, 7454, 9454, 1654, 7654, 3854, 1954, 7954, 3064, 1264, 7364, 9364, 3464, 9464, 1564, 7564, 3664, 3764, 9764, 1964, 3074, 1274, 3274, 9274, 3374, 1574, 9574, 3874, 7874, 9874, 3974, 9974, 1084, 3184, 7184, 1384, 1684, 1784, 7784, 9884, 3094, 9094, 9194, 1394, 3394, 7394, 3494, 1594, 7594, 7694, 9694, 3794, 7894, 3994, 9994, 3005, 9005, 1105, 1205, 3205, 9305, 1505, 9505, 7705, 1805, 7805, 9905, 1015, 7015, 3115, 9115, 7415, 3515, 7615, 1715, 9715, 9815, 7915, 9025, 7225, 1325, 3325, 7325, 1625, 3725, 9725, 1825, 7925, 3035, 9035, 3235, 3335, 7435, 1535, 1835, 7835, 3935, 9935, 7045, 3145, 7145, 9145, 1345, 7345, 1445, 3445, 9445, 1745, 7745, 9745, 3845, 1055, 3055, 7055, 9155, 1255, 7255, 1355, 7555, 3655, 9655, 3755, 1855, 1955, 3265, 9365, 1465, 7465, 1565, 3565, 7565, 9565, 9665, 3865, 9865, 3965, 1075, 1175, 7175, 7375, 1475, 3475, 9475, 9775, 3875, 1975, 1085, 7085, 3185, 1285, 7285, 9385, 3485, 9485, 1585, 7585, 1685, 7685, 9685, 9785, 1885, 7985, 3095, 3295, 7295, 9395, 3595, 1895, 7895, 7006, 1106, 9206, 7306, 3406, 7406, 3506, 7606, 3706, 9706, 9806, 1906, 1016, 3116, 1216, 1316, 3316, 3416, 1516, 3616, 3716, 7916, 9916, 3026, 1126, 7126, 1226, 9226, 7426, 7526, 3626, 9626, 1726, 7726, 7826, 9926, 1036, 1136, 7136, 3236, 9236, 7336, 3436, 3536, 9536, 1636, 7636, 3736, 9736, 9836, 7936, 1246, 7246, 9446, 1546, 9646, 3746, 1846, 1946, 1256, 9256, 7456, 1556, 3556, 3656, 9656, 1756, 7756, 1856, 9956, 7066, 9166, 7366, 3566, 9566, 1666, 3766, 9766, 9866, 1966, 1076, 3076, 9076, 9176, 3376, 7376, 1676, 3676, 9776, 1876, 1976, 3976, 3086, 3286, 7286, 9286, 3386, 1486, 7586, 3686, 9686, 1786, 3886, 9986, 7096, 1196, 7196, 7496, 9496, 9596, 1696, 7696, 1796, 7796, 3896, 1996, 7996, 1007, 3107, 9107, 7207, 9307, 3407, 7507, 9607, 9707, 3017, 9017, 1217, 7217, 9217, 1517, 9517, 7717, 7817, 3917, 7027, 1127, 3127, 9127, 9227, 7327, 3427, 7427, 3527, 3827, 7927, 7037, 9037, 1237, 1337, 3337, 9437, 1537, 9637, 3937, 1147, 7147, 3347, 1547, 7547, 9547, 7747, 1847, 7847, 9847, 9947, 7057, 7157, 3257, 9257, 7357, 1457, 7457, 9457, 9557, 1657, 3757, 7757, 3857, 9857, 1957, 3067, 7067, 1267, 9367, 3467, 9467, 9667, 3767, 1867, 7867, 1967, 9967, 3077, 7177, 3277, 7277, 1477, 3577, 7577, 9577, 9877, 3977, 7187, 3287, 9287, 1487, 3587, 7687, 3787, 7787, 9787, 3887, 1097, 7097, 9197, 7297, 3397, 7397, 9497, 1597, 3697, 3997, 9008, 1108, 7108, 9308, 3508, 9508, 9608, 1808, 7808, 9808, 3908, 1018, 1118, 7118, 3218, 7418, 1618, 7618, 1718, 9718, 1918, 9028, 9128, 1228, 1328, 3328, 7328, 3428, 3628, 9628, 3728, 7828, 1928, 3928, 7928, 1138, 7138, 9238, 3538, 3638, 9638, 7738, 7838, 9838, 9148, 3248, 9248, 1348, 3448, 7448, 1648, 7648, 1058, 3158, 1258, 7258, 7358, 9358, 3458, 3658, 3758, 1858, 7958, 9958, 9068, 3268, 7268, 9268, 1468, 7468, 3668, 9668, 7768, 1868, 9868, 3968, 9968, 7078, 3178, 9178, 1378, 7378, 1478, 7478, 3578, 1678, 9778, 3878, 3088, 7088, 9188, 1288, 1388, 7388, 9388, 9488, 1688, 3688, 7688, 7888, 3988, 3298, 9298, 3398, 1498, 1598, 3698, 9698, 1798, 9998, 1009, 7009, 1109, 3109, 9209, 1409, 3409, 9409, 9509, 7609, 1909, 3019, 9019, 7219, 3319, 7319, 1519, 7519, 1619, 3719, 1819, 7819, 9919, 3029, 9029, 1229, 7229, 9329, 1429, 7529, 7729, 1829, 3829, 3929, 1139, 9139, 3239, 7339, 1439, 3439, 9439, 1739, 7739, 1939, 7939, 3049, 3149, 9149, 1249, 1349, 3349, 7349, 9349, 1649, 3649, 7649, 3749, 9749, 1949, 7949, 1159, 1259, 3359, 9359, 7459, 1559, 7859, 1069, 3169, 9169, 3269, 9269, 1369, 3469, 9469, 1669, 7769, 9769, 9869, 7969, 9179, 1279, 3379, 9379, 3479, 9479, 7679, 9679, 1879, 7879, 1979, 3089, 1189, 7189, 9289, 3389, 9389, 1589, 7589, 9589, 1789, 3889, 7889, 1099, 7099, 3299, 9299, 1399, 1499, 9499, 7699, 3799]

In [ ]:
primosdereversodeprimos=[]
for n in reversodeprimos:
    c=0
    for o in range(1,n):
        if n%o==0:
            c+=1
    if c==1:
        primosdereversodeprimos.append(n)
print(primosdereversodeprimos)

[2, 3, 5, 7, 11, 31, 71, 13, 73, 17, 37, 97, 79, 101, 701, 311, 131, 941, 151, 751, 761, 971, 181, 191, 991, 113, 313, 733, 743, 353, 953, 373, 383, 983, 107, 907, 727, 337, 937, 347, 157, 757, 167, 967, 787, 797, 709, 919, 929, 739, 149, 359, 769, 179, 389, 199, 9001, 1201, 1301, 3301, 1601, 9601, 1901, 7901, 3011, 9011, 1511, 3511, 1811, 3911, 1021, 3121, 7121, 3221, 9221, 1321, 7321, 9421, 9521, 9721, 3821, 1031, 1231, 1831, 9931, 9041, 9241, 9341, 3541, 1741, 7841, 9941, 1151, 3251, 9551, 3851, 7951, 1061, 9161, 7561, 9661, 3271, 3371, 1471, 3571, 9871, 1181, 1381, 7481, 7681, 9781, 1091, 3191, 3391, 9491, 9791, 1103, 9103, 3203, 9403, 7603, 3803, 9803, 9013, 1213, 3613, 9613, 1913, 3023, 1223, 1523, 7523, 1723, 9923, 1033, 9133, 3433, 7433, 9533, 1733, 3733, 9833, 1933, 7043, 3343, 3643, 7643, 9643, 1153, 7253, 1453, 1753, 3853, 3163, 3463, 7963, 9173, 3373, 7673, 3083, 1283, 1583, 3583, 9883, 1193, 7193, 9293, 7207, 3407, 7507, 1217, 7717, 7817, 3917, 7027, 9127, 9227, 3527, 7927, 1237, 9437, 3347, 7547, 9547, 1847, 7057, 3257, 9257, 7457, 1657, 7757, 9857, 3067, 3467, 9467, 3767, 1867, 7867, 9967, 7177, 7577, 7187, 1487, 7687, 9787, 1097, 7297, 9497, 1597, 3697, 1009, 1109, 3109, 9209, 1409, 3019, 7219, 3319, 1619, 3719, 9029, 1229, 7229, 1429, 7529, 3929, 1439, 9439, 3049, 1249, 7349, 9349, 7649, 9749, 1949, 7949, 1259, 3359, 7459, 1559, 1069, 3169, 3469, 1669, 9769, 1279, 9479, 9679, 1879, 7879, 1979, 3089, 3389, 7589, 1789, 3889, 3299, 1399, 1499, 7699]

In [ ]:
import pandas as pd
listaW=[]
listaX=[]
listaY=[]
listaZ=[]
for p in primosyproductoind:
    if int(str(p)[::-1]) in reversodeprimos:
        listaW.append(p)
        listaX.append(primos.index(p)+1)
        listaY.append(int(str(p)[::-1]))
        listaZ.append(primos.index(int(str(p)[::-1]))+1)
        
df1=pd.DataFrame(list(zip(listaW, listaX, listaY, listaZ)), columns =['Primo', 'PosPrimo', 'RevPrimo', 'PosRevPrimo'])
df1

   Primo  PosPrimo  RevPrimo  PosRevPrimo
0     17         7        71           20
1     73        21        37           12

In [ ]:
import pandas as pd
#LISTA DE NÚMEROS DESDE HASTA
desde=1
hasta=200000

#NÚMEROS COMO LISTA
lista=list(range(desde,hasta))

#OBTENER SOLO LOS PRIMOS
primos=[]
for i in lista:
    c=0
    for j in range(1,i):
        if i%j==0:
            c+=1
    if c==1:
        primos.append(i)


#FUNCIÓN CALCULAR PRODUCTO DE NÚMEROS
def productonúmeros(n):
    producto = 1
 
    # NÚMERO ENTERO A CADENA
    ncadena = str(n)
     
    # A TRAVÉS DE LA CADENA
    for k in ncadena:
        producto = producto * int(k)
    return producto

#GENERANDO UNA LISTA DE NÚMEROS PRIMOS CUYO PRODUCTO SEA IGUAL A SU POSICIÓN (EMPEZANDO EN 1) EN LA LISTA
primosyproductoind=[]
for l in primos:
    #Solo números compuestos por dígitos
    if l>9:
        if productonúmeros(l) == primos.index(l)+1:
            primosyproductoind.append(l)

print('Los números primos en la lista desde '+str(desde)+' hasta '+str(hasta)+' que cumplen con que su producto sea igual a la posición que ocupan son:')
print(primosyproductoind)
            
 
##################NÚMEROS ESPEJO DE LOS NÚMEROS PRIMOS DE LA LISTA DADA######################
reversodeprimos=[]
for m in primos:
    a=int(str(m)[::-1])
    reversodeprimos.append(a)

'''
#NÚMEROS PRIMOS DE LA LISTA DE NÚMEROS ESPEJO DE LOS NÚMEROS PRIMOS DE LA LISTA DADA
primosdereversodeprimos=[]
for n in reversodeprimos:
    c=0
    for o in range(1,n):
        if n%o==0:
            c+=1
    if c==1:
        primosdereversodeprimos.append(n)
'''

#CREANDO DATAFRAME CON LOS NÚMEROS PRIMOS QUE CUMPLEN LAS DOS PRIMERAS CONDICIONES CON SU POSICIÓN, NÚMEROS ESPEJO Y POSICIONES DE LOS ESPEJO
listaW=[]
listaX=[]
listaY=[]
listaZ=[]
for p in primosyproductoind:
    if int(str(p)[::-1]) in reversodeprimos:
        listaW.append(p)
        listaX.append(primos.index(p)+1)
        listaY.append(int(str(p)[::-1]))
        listaZ.append(primos.index(int(str(p)[::-1]))+1)
        
df1=pd.DataFrame(list(zip(listaW, listaX, listaY, listaZ)), columns =['Primo', 'PosPrimo', 'RevPrimo', 'PosRevPrimo'])


for q in range(len(df1)):
    if df1['PosPrimo'].values[q] == int(str(df1['PosRevPrimo'].values[q])[::-1]):
        print('')
        print('Los números que cumplen todas las condiciones para la conjetura de Sheldon entre '+str(desde)+' hasta '+str(hasta)+' son: ')
        print(df1['Primo'].values[q])

Los números primos en la lista desde 1 hasta 200000 que cumplen con que su producto sea igual a la posición que ocupan son:
[17, 73]

Los números que cumplen todas las condiciones para la conjetura de Sheldon entre 1 hasta 200000 son:
73